name: CD Example Production
on:
  push:
    branches:
      - main
  
jobs:
    deploy:
      name: CD Example Production
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: SSH Remote Server
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_NAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            port: 22
            script: |
              echo "Successfully connected to the server"
              
              cd /home/cicd/cicd_database_example
              ls  
              echo "Successfully entered the CICD Example Production folder"
              
              sudo docker compose up -d 
              echo "Successfully started Docker Compose"