name : CICD Database Development To Production

on:
  push:
    branches:
      - main 

jobs:
  db_cicd: 
    name : Database CICD
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name : SSH Remote Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: | 
            echo "Berhasil Terhubung Ke Server"

            cd /home/cicd/cicd_database_example
            ls  
            echo "Berhasil Masuk Ke Folder CICD Database Exercise"

            sudo docker compose up -d 
            echo "Berhasil Menjalankan Docker Compose"

            if [ -d " .git" ]; then
              echo "Git directory exists, pulling latest changes"
              git pull origin main
            else
              echo "Git directory does not exist, cloning repository"
              git clone
            fi